Michiocre backend
Gabsii/spoti-vote pull request #240
Opened 2020-10-03 22:39 UTC by Michiocre

Wrapped the console.log command and added a api function to access older logs (currently open to anyone).

Also small update to the current data storage system

2020-10-04 12:36 UTC, Gabsii requested changes

2020-10-04 12:36 UTC, Gabsii commented on backend/api/callback.js
> +
remove empty line

2020-10-04 12:36 UTC, Gabsii commented on backend/handler/handler.js
> +    fs.appendFile(logsLoc, `[${datetime.toISOString()}] ${type ? type : 'log'} : ${message} <br>`, function (err) {
the ternary can be removed if you set `type = 'log'` as a default parameter

2020-10-04 22:26 UTC, Gabsii commented
Is this PR ready for review? Otherwise, turn it into a draft PR please.

2020-10-05 21:11 UTC, Michiocre commented
Is ready for review now.
The backend testing hasn't really been implemented yet only the framework.
Adding new test will be pretty easy from now on.
Im not too sure about the testing structure so it might get changed again.

I wont be able to split the data files into one for each room since i have a few functions like getRoomByName, getRoomByHostToken, getRoomById. And for these to work i need to have all the room in a array.
So by keeping all the rooms in a single file there is less time spent on file management.
The files have been optimized a bit there shouldn't be as much unused data floating around.

I also finally fixed the labeler correctly so you shouldn't be getting a failed workflow email with every push.

2021-01-20 01:17 UTC, closed without merging